### PR TITLE
while instead of for

### PR DESCRIPTION
**Pull request by timdp**
On my machine (Windows, Node v4.1.1 x64), 100k iterations of `test.js` take 21 seconds with this patch, compared to 38 seconds for master.

I'm sure caching `a.length` has something to do with it as well, but still, intuitively, it feels faster to me.

### CODE REVIEW

**Comment by timdp** [comment]
Err. I'm getting 21 seconds for master now as well. Maybe Windows was doing something in the background. I guess it doesn't matter for performance then.

Maybe for readability? We used to teach our students that you should use a while loop if you're planning to break early, but there are of course many philosophies.

(Sigh.)

**Comment by sindresorhus** [comment]
Since the perf is the same I prefer to keep the exising as I personally feel the intent is clearer with that code.

**Comment by timdp** [comment]
Can't say I disagree in the end. :-)

**Comment by dcousens** [comment]
There is technically more conditionals in this algorithm,  if its faster is just a JS quirk that probably shouldn't be relied on.

**Comment by timdp** [comment]
@dcousens Out of curiosity: the only extra conditional would be the `return (i === length)` at the very end, right? In amortized performance, it won't matter, but it won't improve things either, of course.

I've also been told that the `return` in the `for` loop can lead to performance degradation, but since the benchmarks contradict it, I guess it's a common misconception.

I'm going to delete my fork, since it's become kinda useless.

**Comment by dcousens** [comment]
> Out of curiosity: the only extra conditional would be the return (i === length) at the very end, right?

Yes,  but it also enforces a comparison even when `a.length === 0`.

>  In amortized performance, it won't matter, but it won't improve things either, of course.

Of course, there is no doubt this would be incredibly difficult to actually measure (in JS).

**Pull request closed without merging**
